functionality:
  name: generate_report
  description: A minimal example component.
  arguments:
    - type: file
      name: --input
      example: data.csv
      required: true
    - type: integer
      name: --year
      example: 2012
      required: true
    - type: integer
      name: --min_duration_per_project
      example: 100
      required: true
    - type: file
      name: --output
      direction: output
      example: filtered.csv
      required: true
  resources:
    - type: python_script
      path: filter_timesheets.py
platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: apt
        packages:
          - curl
          - wget
      - type: python
        packages:
          - anndata
          - pandas