functionality:
  name: example2_python_with_setup
  description: A minimal example component.
  arguments:
    - type: file
      name: --input
      example: filtered.csv
      required: true
    - type: file
      name: --output
      direction: output
      example: report.pdf
      required: true
  resources:
    - type: python_script
      path: generate_report.py
platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: apt
        packages:
          - curl
          - wget
      - type: python
        packages:
          - anndata
          - pandas
          - matplotlib
          - reportlab
  - type: nextflow